### ISSUE TITLE
Consider an algorithm to determine the amount of Henkaku tokens needed for register

### ISSUE THREAD

**Issue by yawn-c111** [henkaku-center/henkaku-nengajo-contract#13]
- [ ] implement a function for calculate price

**Comment by dueyama** [comment]
こちらは、note にある、年賀状の発行数が多いほど単価が上がるということを実装すれば良いということでしょうか？

**Comment by yawn-c111** [comment]
@dueyama 
そうですね！
私の場合は、一枚あたりに必要なHenkakuの単価というよりは、指定された発行数に必要なHenkakuの合計量というイメージを持っていたのですが、計算のしやすさ次第でどちらを選んでも良い気がしました。

ここはkarawapoさん、yukiさんにご相談した方がよい部分な気がしていますが、とりあえず今までアドバイスいただいたこととしては、
- 階段状の条件を試案して、計算しながら妥当性を考えてみる
- 可能であれば、Quadratic Fundingのような形でなめらかな計算式を考えてみる
という感じな気がします！

**Comment by dueyama** [comment]
まずは仕様を決めるということですね！了解です！

**Comment by yu23ki14** [comment]
X=登録枚数
Y=必要HENKAKU数
として以下でいかがでしょうか？
Y=10+5(X>10)(X<101)(X-10)+10(X>100)(X-100)

**Comment by yawn-c111** [comment]
数学自信がないのですが、確認させてください！
```
Y=10+5(X>10)(X<101)(X-10)+10(X>100)(X-100)

X <= 10 のとき
Y = 10

10 < X < 101 のとき
Y = 10 + 5( X - 10 ) = 5X - 40

101 <= X のとき
Y = 10 + 10( X - 100 ) = 10X - 990
```
で合っているでしょうか？
これだとだいぶ101枚以降が有利になる気がしました。

```
X = 99 のとき
Y = 10 + 5( 99 - 10 ) = 10 + 445 = 455

X = 100 のとき
Y = 10 + 5( 100 - 10 ) = 10 + 450 = 460

X = 101 のとき
Y = 10 + 10( 101 - 100 ) = 10 + 10 = 20

X = 102 のとき
Y = 10 + 10( 102 - 100 ) = 10 + 20 = 30
```
11枚目以降は1枚あたり、5ずつ
101枚目以降は1枚あたり、さらに5ずつ、つまり10ずつ増えていくのかなと思ったので、
```
Y=10+5(X>10)(X-10)+5(X>100)(X-100)

101 <= X のとき
Y = 10 + 5( X - 10 ) + 5( X - 100 ) = 10X - 540

なので、
X = 101 のとき
Y = 10 + 5( 101 - 10 ) + 5( 101 - 100 ) = 10 + 455 + 5 = 470

X = 102 のとき
Y = 10+ 5( 102 - 10 ) + 5( 102 - 100 ) = 10 + 460 + 10 = 480
```
はどうかと思ったのですが、いかがでしょうか？

**Comment by RyuKiyo66** [comment]
Y=10+5(X>10)(X<101)(X-10)+5(X>100)(X-100)です。

**Comment by yu23ki14** [comment]
@yawn-c111 
- 10枚までは$10 固定
- 11枚から100枚までは$5 x 枚数
- 101枚からは$10 x 枚数

50枚のときは、最初の10枚の$10、残りの40枚 x $5 の足し算なので、210 HENKAKU
130枚のときは、最初の10枚の$10、100枚までの90枚 x $5、残りの30枚 x $10 の足し算なので、760 HENKAKU
になります！

**Comment by RyuKiyo66** [comment]
その理解です。

**Comment by yawn-c111** [comment]
なるほど、ありがとうございます！

では私がコードに実装するときは、
```
X <= 10 のとき
Y = 10

10 < X < 101 のとき
Y = 5X - 40

101 <= X のとき
Y = 10X - 540
```
で実装すればよい感じでしょうか？

**Comment by yu23ki14** [comment]
@yawn-c111 
良いです！
