### ISSUE TITLE
Create a function for retrieving holding Nengajo Metadata URI

### ISSUE THREAD

**Issue by yu23ki14** [henkaku-center/henkaku-nengajo-contract#24]
Please implement a function which returns token metadata URI with using retrieveMintedNengajoIds function

**Comment by dueyama** [comment]
これは、すでにある url 関数のように、 tokenID が与えられた時にそれが mint されているかどうかを、retrieveMintedNengajoIds を呼んで、その中に ID があるかをチェックしてあれば、その uri を返し、なければ require で　"Nengajo: not minted" とすれば良いという感じですか？

**Comment by yu23ki14** [comment]
@dueyama 
やりたいことは、保持している年賀状NFTのuriを配列で返すことです。

retrieveMintedNengajoIds を呼び出して返ってくるのはidの配列ですので、各 id に紐づくuriを uri関数をつかって引っ張ってきて、配列にして返すという感じでお願いします。
retrieveMintedNengajoIds で空の配列の場合は、uriの配列も空の配列で大丈夫です。

**Comment by dueyama** [comment]
//@retrun holding nengajo's metadata URIs
    function retriveMintedNengajoURIs() public view returns (string[] memory) {
        uint256[] memory mintedNengajoIds = retrieveMintedNengajoIds();
        string[] memory mintedNengajoURIs_ = new string[](mintedNengajoIds.length);

        for (uint256 i = 0; i < mintedNengajoIds.length; ++i) {
            mintedNengajoURIs_[i] = uri(mintedNengajoIds[i]);
        }

        return mintedNengajoURIs_;
    }

こんな感じでしょうか？
