### ISSUE TITLE
Create event emit

### ISSUE THREAD

**Issue by yu23ki14** [henkaku-center/henkaku-nengajo-contract#26]
- registerCreative
- mintBatch
- mint

**Comment by dueyama** [comment]
Badge のからの推測ですが、こんな感じのを emit したらよいのでしょうか？

event Mint(address indexed minter, uint256 indexed tokenId);
event MintBatch(address indexed minter, uint256 tokenId[]);
event RegisterCreative(address indexed creator, string metaDataURL, uint256 maxSupply);

indexed が調べた範囲での理解だと、 tokenId[] とか、 metaDataURL, maxSupply につけても意味なさそうなのでつけませんでした。

**Comment by yu23ki14** [comment]
そうですね！
