### ISSUE TITLE
Implement a function for registering nengajo and retrieving registered nengajoes

### ISSUE THREAD

**Issue by yu23ki14** [henkaku-center/henkaku-nengajo-contract#4]
- [x] Consider nengajo struct
- [x] implement listing function
- [x] implement retrieving lited nengajoes function
- [x] limit num of max supply for each nengajo
- [ ] Check amount of sent HENKAKU Token 
- [ ] Hand over sent HENKAKU Token to Henkaku pool wallet

**Comment by yawn-c111** [comment]
@yu23ki14 

Nengajo.solの`registerCreative`関数の`_tokenIds.increment();`について

```solidity
  function registerCreative(uint256 _maxSupply, string memory _metaDataURL) public  {
      _tokenIds.increment();
      uint256 tokenId = _tokenIds.current();
      _setURI(tokenId, _metaDataURL);
      maxSupply[tokenId] = _maxSupply;
  }
```

こちらの順番だと一番最初にregisterされる年賀状の`_tokenIds`は`1`になるかと思うのですが、順番を変えて`_tokenIds.increment();`を最後にして、`0`始まりにしても大丈夫でしょうか？

```solidity
  function registerCreative(uint256 _maxSupply, string memory _metaDataURL) public  {
      uint256 tokenId = _tokenIds.current();
      _setURI(tokenId, _metaDataURL);
      maxSupply[tokenId] = _maxSupply;
      _tokenIds.increment();
  }
```

structを配列にして`NengajoStruct[] nengajos`のような形を検討していて、それにpushで情報を加えていこうかと考えていたのですが、`_tokenIds`が`0`始まりだとstructの配列の順番`nengajos[0]`と連動するので分かりやすいかと考えました！

何か理由がありましたら、別の方法を検討できると思います！
