### ISSUE TITLE
Mintingでmintされない

### ISSUE THREAD

**Issue by morizo0** [henkaku-center/henkaku-nengajo-contract#62]
あけましておめでとうございます！いつも楽しくポッドキャスト拝聴させていただいております。

人生で初めて、mintを年賀状NFTでしようと試みているのですが、何度やっても手元にNFTが届かない状況です。

Mac で chrome に metamask を入れてやっているのですが、ガス代は払っているようなのですが、何かやり方を間違えているのでしょうか？

お教えいただければと存じます。

**Comment by yu23ki14** [comment]
@morizo0 
問題の報告ありがとうございます。エンジニアのりょーまです。
Podcastの年賀状受け取りができないということでよろしいでしょうか？

止まってしまう直前の画面のスクリーンショットを貼り付けられますでしょうか？
調査しやすくなりますので、お手数ですが追加情報お待ちしております。よろしくお願いします。

**Comment by morizo0** [comment]
りょーまさん、返信ありがとうございます。　添付のように、Mintingで止まってしまいます。
![スクリーンショット 2023-01-05 13 30 54](https://user-images.githubusercontent.com/121774653/210702191-7a3179f9-50c1-4f4c-b9bb-6c2cd099df3c.png)

**Comment by morizo0** [comment]
この画面が出ている時、Metamaskのポップアップが出てきてそこで、決済を何度か行っております。
決済はできてるようなのですがなぜか、ガス代はかかるのですが、NFTが手元にきていない状況です。

**Comment by yu23ki14** [comment]
@morizo0 さんはHENKAKU Communityのメンバーでしょうか？Podcastの年賀状は誰でもMintできますが、トップページに並んでいるものはHenkaku Communityのコミュニティトークンを持っていることが条件となります。
すでにコミュニティメンバーでしたら大変失礼しました。HENKAKUを稼いでからMintしていただけると幸いです。
もしコミュニティメンバーでなければ、こちらから申請できますので承認をお待ち下さい。https://airtable.com/shrbDbYUBoFgkg0tY

**Comment by morizo0** [comment]
トップページに並んでるものは、Henkaku トークンを持っていないといけなかったんですね！
メンバーではないので、それが原因でした、、ご返信ありがとうございます。申請させていただきます。

**Comment by morizo0** [comment]
申請させていただきました！
